server:
    port: 8763
spring:
    application:
        name: remote-config-server
    cloud:
        config:
            server:
                # git仓库配置信息
                git:
                    # git仓库地址
                    uri: https://github.com/MrStrangeL/SpringCloudSouthWindStudy.git
                    # 配置文件路径
                    searchPaths: config
                    # 访问git仓库的用户名
                    username:
                    # 访问git仓库的密码
                    password:
            label: master
eureka:
    client:
        service-url:
            # 注册中心的访问地址
            defaultZone: http://localhost:8761/eureka/