server:
  port: 8030
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
zuul:
  routes:
    provider:
#      path: /student/**
#      serviceId: provider
#      # 在转发时，所有的/student/**转发给listOfServers，stripPrefix为true时去掉path前缀，为false时不去掉path前缀
#      stripPrefix: false
      path: /p/**
      serviceId: provider
      stripPrefix: true
    consumer:
      path: /c/**
      serviceId: consumer
      stripPrefix: true
ribbon:
  eureka:
    enabled: false
provider:
  ribbon:
    listOfServers: http://localhost:8010/,http://localhost:8050/
consumer:
  ribbon:
    listOfServers: http://localhost:8020/