server:
    port: 8091
spring:
    application:
        name: remote-config-client
management:
    security:
        enabled: false
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/